// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// align_signs_cpp
arma::mat align_signs_cpp(arma::mat u_boot, const arma::mat& u_obs);
RcppExport SEXP _plsrri_align_signs_cpp(SEXP u_bootSEXP, SEXP u_obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type u_boot(u_bootSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type u_obs(u_obsSEXP);
    rcpp_result_gen = Rcpp::wrap(align_signs_cpp(u_boot, u_obs));
    return rcpp_result_gen;
END_RCPP
}
// boot_test_task_cpp
Rcpp::List boot_test_task_cpp(const arma::mat& stacked_datamat, const arma::imat& bootsamp, const arma::mat& observed_u, int num_groups, const arma::ivec& num_subj_lst, int num_cond, int meancentering_type);
RcppExport SEXP _plsrri_boot_test_task_cpp(SEXP stacked_datamatSEXP, SEXP bootsampSEXP, SEXP observed_uSEXP, SEXP num_groupsSEXP, SEXP num_subj_lstSEXP, SEXP num_condSEXP, SEXP meancentering_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type stacked_datamat(stacked_datamatSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type bootsamp(bootsampSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type observed_u(observed_uSEXP);
    Rcpp::traits::input_parameter< int >::type num_groups(num_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_subj_lst(num_subj_lstSEXP);
    Rcpp::traits::input_parameter< int >::type num_cond(num_condSEXP);
    Rcpp::traits::input_parameter< int >::type meancentering_type(meancentering_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_test_task_cpp(stacked_datamat, bootsamp, observed_u, num_groups, num_subj_lst, num_cond, meancentering_type));
    return rcpp_result_gen;
END_RCPP
}
// compute_bsr_cpp
arma::mat compute_bsr_cpp(const arma::mat& u_sum, const arma::mat& u_sq_sum, const arma::mat& observed_u, int num_boot);
RcppExport SEXP _plsrri_compute_bsr_cpp(SEXP u_sumSEXP, SEXP u_sq_sumSEXP, SEXP observed_uSEXP, SEXP num_bootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type u_sum(u_sumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type u_sq_sum(u_sq_sumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type observed_u(observed_uSEXP);
    Rcpp::traits::input_parameter< int >::type num_boot(num_bootSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_bsr_cpp(u_sum, u_sq_sum, observed_u, num_boot));
    return rcpp_result_gen;
END_RCPP
}
// boot_test_task_reduced_cpp
Rcpp::List boot_test_task_reduced_cpp(const arma::mat& task_scores, const arma::mat& task_loadings, const arma::mat& stacked_datamat, const arma::imat& bootsamp, const arma::mat& observed_v, const arma::mat& stacked_designdata, int num_groups, const arma::ivec& num_subj_lst, int num_cond, int method);
RcppExport SEXP _plsrri_boot_test_task_reduced_cpp(SEXP task_scoresSEXP, SEXP task_loadingsSEXP, SEXP stacked_datamatSEXP, SEXP bootsampSEXP, SEXP observed_vSEXP, SEXP stacked_designdataSEXP, SEXP num_groupsSEXP, SEXP num_subj_lstSEXP, SEXP num_condSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type task_scores(task_scoresSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type task_loadings(task_loadingsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type stacked_datamat(stacked_datamatSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type bootsamp(bootsampSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type observed_v(observed_vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type stacked_designdata(stacked_designdataSEXP);
    Rcpp::traits::input_parameter< int >::type num_groups(num_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_subj_lst(num_subj_lstSEXP);
    Rcpp::traits::input_parameter< int >::type num_cond(num_condSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_test_task_reduced_cpp(task_scores, task_loadings, stacked_datamat, bootsamp, observed_v, stacked_designdata, num_groups, num_subj_lst, num_cond, method));
    return rcpp_result_gen;
END_RCPP
}
// perm_test_task_cpp
arma::ivec perm_test_task_cpp(const arma::mat& stacked_datamat, const arma::imat& permsamp, const arma::vec& observed_s, int num_groups, const arma::ivec& num_subj_lst, int num_cond, int meancentering_type);
RcppExport SEXP _plsrri_perm_test_task_cpp(SEXP stacked_datamatSEXP, SEXP permsampSEXP, SEXP observed_sSEXP, SEXP num_groupsSEXP, SEXP num_subj_lstSEXP, SEXP num_condSEXP, SEXP meancentering_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type stacked_datamat(stacked_datamatSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type permsamp(permsampSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type observed_s(observed_sSEXP);
    Rcpp::traits::input_parameter< int >::type num_groups(num_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type num_subj_lst(num_subj_lstSEXP);
    Rcpp::traits::input_parameter< int >::type num_cond(num_condSEXP);
    Rcpp::traits::input_parameter< int >::type meancentering_type(meancentering_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_test_task_cpp(stacked_datamat, permsamp, observed_s, num_groups, num_subj_lst, num_cond, meancentering_type));
    return rcpp_result_gen;
END_RCPP
}
// perm_test_fast_cpp
arma::ivec perm_test_fast_cpp(const Rcpp::List& task_means_lst, const arma::imat& permsamp, const arma::vec& observed_s);
RcppExport SEXP _plsrri_perm_test_fast_cpp(SEXP task_means_lstSEXP, SEXP permsampSEXP, SEXP observed_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type task_means_lst(task_means_lstSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type permsamp(permsampSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type observed_s(observed_sSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_test_fast_cpp(task_means_lst, permsamp, observed_s));
    return rcpp_result_gen;
END_RCPP
}
// procrustes_cpp
arma::mat procrustes_cpp(const arma::mat& X, const arma::mat& Y, bool scale);
RcppExport SEXP _plsrri_procrustes_cpp(SEXP XSEXP, SEXP YSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(procrustes_cpp(X, Y, scale));
    return rcpp_result_gen;
END_RCPP
}
// procrustes_boot_cpp
Rcpp::List procrustes_boot_cpp(const arma::mat& X, const arma::mat& Y, int max_iter, double tol);
RcppExport SEXP _plsrri_procrustes_boot_cpp(SEXP XSEXP, SEXP YSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(procrustes_boot_cpp(X, Y, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// colwise_cor_cpp
arma::vec colwise_cor_cpp(const arma::mat& X, const arma::mat& Y);
RcppExport SEXP _plsrri_colwise_cor_cpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(colwise_cor_cpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// task_mean_cpp
arma::mat task_mean_cpp(const arma::mat& datamat, int n_subj, int n_cond);
RcppExport SEXP _plsrri_task_mean_cpp(SEXP datamatSEXP, SEXP n_subjSEXP, SEXP n_condSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type datamat(datamatSEXP);
    Rcpp::traits::input_parameter< int >::type n_subj(n_subjSEXP);
    Rcpp::traits::input_parameter< int >::type n_cond(n_condSEXP);
    rcpp_result_gen = Rcpp::wrap(task_mean_cpp(datamat, n_subj, n_cond));
    return rcpp_result_gen;
END_RCPP
}
// normalize_rows_cpp
arma::mat normalize_rows_cpp(const arma::mat& X);
RcppExport SEXP _plsrri_normalize_rows_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_rows_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// xcor_pearson_cpp
arma::mat xcor_pearson_cpp(const arma::mat& design, const arma::mat& datamat);
RcppExport SEXP _plsrri_xcor_pearson_cpp(SEXP designSEXP, SEXP datamatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type datamat(datamatSEXP);
    rcpp_result_gen = Rcpp::wrap(xcor_pearson_cpp(design, datamat));
    return rcpp_result_gen;
END_RCPP
}
// xcor_cov_cpp
arma::mat xcor_cov_cpp(const arma::mat& design, const arma::mat& datamat);
RcppExport SEXP _plsrri_xcor_cov_cpp(SEXP designSEXP, SEXP datamatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type datamat(datamatSEXP);
    rcpp_result_gen = Rcpp::wrap(xcor_cov_cpp(design, datamat));
    return rcpp_result_gen;
END_RCPP
}
// xcor_cosine_cpp
arma::mat xcor_cosine_cpp(const arma::mat& design, const arma::mat& datamat);
RcppExport SEXP _plsrri_xcor_cosine_cpp(SEXP designSEXP, SEXP datamatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type datamat(datamatSEXP);
    rcpp_result_gen = Rcpp::wrap(xcor_cosine_cpp(design, datamat));
    return rcpp_result_gen;
END_RCPP
}
// xcor_dot_cpp
arma::mat xcor_dot_cpp(const arma::mat& design, const arma::mat& datamat);
RcppExport SEXP _plsrri_xcor_dot_cpp(SEXP designSEXP, SEXP datamatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type datamat(datamatSEXP);
    rcpp_result_gen = Rcpp::wrap(xcor_dot_cpp(design, datamat));
    return rcpp_result_gen;
END_RCPP
}
// pls_xcor_cpp
arma::mat pls_xcor_cpp(const arma::mat& design, const arma::mat& datamat, int cormode);
RcppExport SEXP _plsrri_pls_xcor_cpp(SEXP designSEXP, SEXP datamatSEXP, SEXP cormodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type datamat(datamatSEXP);
    Rcpp::traits::input_parameter< int >::type cormode(cormodeSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_xcor_cpp(design, datamat, cormode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plsrri_align_signs_cpp", (DL_FUNC) &_plsrri_align_signs_cpp, 2},
    {"_plsrri_boot_test_task_cpp", (DL_FUNC) &_plsrri_boot_test_task_cpp, 7},
    {"_plsrri_compute_bsr_cpp", (DL_FUNC) &_plsrri_compute_bsr_cpp, 4},
    {"_plsrri_boot_test_task_reduced_cpp", (DL_FUNC) &_plsrri_boot_test_task_reduced_cpp, 10},
    {"_plsrri_perm_test_task_cpp", (DL_FUNC) &_plsrri_perm_test_task_cpp, 7},
    {"_plsrri_perm_test_fast_cpp", (DL_FUNC) &_plsrri_perm_test_fast_cpp, 3},
    {"_plsrri_procrustes_cpp", (DL_FUNC) &_plsrri_procrustes_cpp, 3},
    {"_plsrri_procrustes_boot_cpp", (DL_FUNC) &_plsrri_procrustes_boot_cpp, 4},
    {"_plsrri_colwise_cor_cpp", (DL_FUNC) &_plsrri_colwise_cor_cpp, 2},
    {"_plsrri_task_mean_cpp", (DL_FUNC) &_plsrri_task_mean_cpp, 3},
    {"_plsrri_normalize_rows_cpp", (DL_FUNC) &_plsrri_normalize_rows_cpp, 1},
    {"_plsrri_xcor_pearson_cpp", (DL_FUNC) &_plsrri_xcor_pearson_cpp, 2},
    {"_plsrri_xcor_cov_cpp", (DL_FUNC) &_plsrri_xcor_cov_cpp, 2},
    {"_plsrri_xcor_cosine_cpp", (DL_FUNC) &_plsrri_xcor_cosine_cpp, 2},
    {"_plsrri_xcor_dot_cpp", (DL_FUNC) &_plsrri_xcor_dot_cpp, 2},
    {"_plsrri_pls_xcor_cpp", (DL_FUNC) &_plsrri_pls_xcor_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_plsrri(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
