# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sign Flip Alignment
#'
#' Aligns bootstrap u vectors to observed u by sign flipping.
#'
#' @param u_boot Bootstrap u matrix
#' @param u_obs Observed u matrix
#' @return Sign-aligned u_boot
#'
#' @keywords internal
align_signs_cpp <- function(u_boot, u_obs) {
    .Call(`_plsrri_align_signs_cpp`, u_boot, u_obs)
}

#' Fast Bootstrap Test for Task PLS
#'
#' Runs the inner loop of bootstrap testing for task PLS.
#' Accumulates bootstrap saliences for SE computation.
#'
#' @param stacked_datamat Stacked data matrix
#' @param bootsamp Bootstrap sample matrix (total_rows x num_boot)
#' @param observed_u Observed u (saliences)
#' @param num_groups Number of groups
#' @param num_subj_lst Subjects per group
#' @param num_cond Number of conditions
#' @param meancentering_type Mean-centering type
#'
#' @return List with u_sum and u_sq_sum
#'
#' @keywords internal
boot_test_task_cpp <- function(stacked_datamat, bootsamp, observed_u, num_groups, num_subj_lst, num_cond, meancentering_type) {
    .Call(`_plsrri_boot_test_task_cpp`, stacked_datamat, bootsamp, observed_u, num_groups, num_subj_lst, num_cond, meancentering_type)
}

#' Compute Bootstrap Ratio
#'
#' Computes bootstrap ratio (u / SE) from accumulated sums.
#'
#' @param u_sum Sum of bootstrap u
#' @param u_sq_sum Sum of squared bootstrap u
#' @param observed_u Observed u
#' @param num_boot Number of bootstrap samples
#'
#' @return Bootstrap ratio matrix
#'
#' @keywords internal
compute_bsr_cpp <- function(u_sum, u_sq_sum, observed_u, num_boot) {
    .Call(`_plsrri_compute_bsr_cpp`, u_sum, u_sq_sum, observed_u, num_boot)
}

#' Fast Permutation Test for Task PLS
#'
#' Runs the inner loop of permutation testing for task PLS.
#' Computes singular values for each permutation and compares to observed.
#'
#' @param stacked_datamat Stacked data matrix
#' @param permsamp Permutation sample matrix (total_rows x num_perm)
#' @param observed_s Observed singular values
#' @param num_groups Number of groups
#' @param num_subj_lst Subjects per group
#' @param num_cond Number of conditions
#' @param meancentering_type Mean-centering type
#'
#' @return Vector of counts (permuted s >= observed s)
#'
#' @keywords internal
perm_test_task_cpp <- function(stacked_datamat, permsamp, observed_s, num_groups, num_subj_lst, num_cond, meancentering_type) {
    .Call(`_plsrri_perm_test_task_cpp`, stacked_datamat, permsamp, observed_s, num_groups, num_subj_lst, num_cond, meancentering_type)
}

#' Fast Permutation Test with Pre-computed Cross-block Matrices
#'
#' More efficient version that pre-computes task means and only shuffles.
#'
#' @param task_means_lst List of task mean matrices by group
#' @param permsamp Permutation sample matrix
#' @param observed_s Observed singular values
#'
#' @return Vector of counts
#'
#' @keywords internal
perm_test_fast_cpp <- function(task_means_lst, permsamp, observed_s) {
    .Call(`_plsrri_perm_test_fast_cpp`, task_means_lst, permsamp, observed_s)
}

#' Procrustes Rotation
#'
#' Aligns matrix Y to matrix X using Procrustes rotation.
#' Finds orthogonal matrix Q that minimizes ||X - Y*Q||_F
#'
#' @param X Target matrix
#' @param Y Source matrix to rotate
#' @param scale Allow scaling (default false)
#'
#' @return Rotated Y matrix
#'
#' @export
procrustes_cpp <- function(X, Y, scale = FALSE) {
    .Call(`_plsrri_procrustes_cpp`, X, Y, scale)
}

#' Procrustes Rotation with Sign Flipping
#'
#' First tries simple sign flipping for each column,
#' then falls back to full Procrustes if needed.
#'
#' @param X Target matrix
#' @param Y Source matrix
#' @param max_iter Maximum iterations for optimization
#' @param tol Tolerance for convergence
#'
#' @return List with rotated Y and rotation matrix
#'
#' @export
procrustes_boot_cpp <- function(X, Y, max_iter = 100L, tol = 1e-8) {
    .Call(`_plsrri_procrustes_boot_cpp`, X, Y, max_iter, tol)
}

#' Fast Column-wise Correlation
#'
#' Computes correlation between corresponding columns of two matrices.
#'
#' @param X First matrix
#' @param Y Second matrix
#'
#' @return Vector of correlations
#'
#' @keywords internal
colwise_cor_cpp <- function(X, Y) {
    .Call(`_plsrri_colwise_cor_cpp`, X, Y)
}

#' Fast Task Mean Computation
#'
#' Computes task means from stacked data matrix.
#'
#' @param datamat Data matrix (n_subj*n_cond x n_features)
#' @param n_subj Number of subjects
#' @param n_cond Number of conditions
#'
#' @return Task mean matrix (n_cond x n_features)
#'
#' @export
task_mean_cpp <- function(datamat, n_subj, n_cond) {
    .Call(`_plsrri_task_mean_cpp`, datamat, n_subj, n_cond)
}

#' Fast Row Normalization
#'
#' Normalizes each row to unit L2 norm.
#'
#' @param X Matrix to normalize
#'
#' @return Normalized matrix
#'
#' @export
normalize_rows_cpp <- function(X) {
    .Call(`_plsrri_normalize_rows_cpp`, X)
}

#' Fast Cross-Correlation (Pearson)
#'
#' Computes Pearson correlation between design and data matrices.
#'
#' @param design Design matrix (n_obs x n_design)
#' @param datamat Data matrix (n_obs x n_features)
#' @return Cross-correlation matrix (n_design x n_features)
#'
#' @keywords internal
xcor_pearson_cpp <- function(design, datamat) {
    .Call(`_plsrri_xcor_pearson_cpp`, design, datamat)
}

#' Fast Cross-Covariance
#'
#' Computes covariance between design and data matrices.
#'
#' @param design Design matrix (n_obs x n_design)
#' @param datamat Data matrix (n_obs x n_features)
#' @return Cross-covariance matrix (n_design x n_features)
#'
#' @keywords internal
xcor_cov_cpp <- function(design, datamat) {
    .Call(`_plsrri_xcor_cov_cpp`, design, datamat)
}

#' Fast Cross-Correlation (Cosine Angle)
#'
#' Computes cosine similarity between design and data matrices.
#'
#' @param design Design matrix (n_obs x n_design)
#' @param datamat Data matrix (n_obs x n_features)
#' @return Cross-correlation matrix (n_design x n_features)
#'
#' @keywords internal
xcor_cosine_cpp <- function(design, datamat) {
    .Call(`_plsrri_xcor_cosine_cpp`, design, datamat)
}

#' Fast Cross-Correlation (Dot Product)
#'
#' Computes dot product between design and data matrices.
#'
#' @param design Design matrix (n_obs x n_design)
#' @param datamat Data matrix (n_obs x n_features)
#' @return Cross-product matrix (n_design x n_features)
#'
#' @keywords internal
xcor_dot_cpp <- function(design, datamat) {
    .Call(`_plsrri_xcor_dot_cpp`, design, datamat)
}

#' Fast Cross-Correlation (All Modes)
#'
#' Computes cross-correlation using specified correlation mode.
#'
#' @param design Design matrix (n_obs x n_design)
#' @param datamat Data matrix (n_obs x n_features)
#' @param cormode Correlation mode: 0=Pearson, 2=Cov, 4=Cosine, 6=Dot
#' @return Cross-correlation matrix (n_design x n_features)
#'
#' @export
pls_xcor_cpp <- function(design, datamat, cormode = 0L) {
    .Call(`_plsrri_pls_xcor_cpp`, design, datamat, cormode)
}

